/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'tamang_food_service_food_ordering_app';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String GOOGLE = 'assets/images/Google.png';
  static const String ILLUSTRATIONS3 = 'assets/images/Illustrations3.png';
  static const String OPENDOODLES = 'assets/images/OpenDoodles.png';
  static const String FEATUREDPARTNERS1 = 'assets/images/featuredpartners1.png';
  static const String FEATUREDPARTNERS2 = 'assets/images/featuredpartners2.png';
  static const String FEATUREDPARTNERS3 = 'assets/images/featuredpartners3.png';
  static const String FEATUREDPARTNERS4 = 'assets/images/featuredpartners4.png';
  static const String FEATUREDPARTNERS5 = 'assets/images/featuredpartners5.png';
  static const String FEATUREDPARTNERS6 = 'assets/images/featuredpartners6.png';
  static const String FOOD = 'assets/images/food.png';
  static const String FOOD1 = 'assets/images/food1.png';
  static const String FOOD2 = 'assets/images/food2.png';
  static const String ITEM = 'assets/images/item.png';
  static const String ITEM1 = 'assets/images/item1.png';
  static const String MAP = 'assets/images/map.png';
  static const String MAP1 = 'assets/images/map1.png';
  static const String SEAFOOD = 'assets/images/seafood.png';
  static const String SEAFOOD1 = 'assets/images/seafood1.png';
  static const String SEAFOOD2 = 'assets/images/seafood2.png';
  static const String TOPPICK = 'assets/images/toppick.png';
  static const String TOPPICK1 = 'assets/images/toppick1.png';
  static const String TOPPICK2 = 'assets/images/toppick2.png';
  static const String TOPPICK3 = 'assets/images/toppick3.png';
  static const String TOPPICK4 = 'assets/images/toppick4.png';
  static const String TOPPICK5 = 'assets/images/toppick5.png';
}
