/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'tamang_food_service_food_ordering_app';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String GOOGLE = 'assets/images/Google.png';
  static const String ILLUSTRATIONS3 = 'assets/images/Illustrations3.png';
  static const String OPENDOODLES = 'assets/images/OpenDoodles.png';
}
